version: "3"

services: 
  db:
    image: mariadb:latest
    container_name: "db1"
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./:/var/www/html/"
    networks: 
      - fullstack
  web:
    image: php:7.2-apache
    container_name: "web1"
    volumes:
      - "./:/var/www/html/"
    ports:
      - "8100:80"
    networks: 
      - fullstack

networks: 
  fullstack:
